version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: barbershop_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: barbershop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - barbershop_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barbershop_backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/barbershop_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: 1234
      JWT_SECRET: 586E3272357538782F413F4428472B4B6250655368566B597033733676397928
      JWT_EXPIRATION: 3600000
      CORS_ALLOWED_ORIGINS: http://localhost:4200,https://barbershop-app.com
      CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE
      CORS_ALLOWED_HEADERS: "*"
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - barbershop_net

volumes:
  postgres_data:

networks:
  barbershop_net:
